---
title: "GO_Reactome_enrich_Imputed_proteins"
output: html_document
date: "2023-12-06"
---



# Load Libraries 
```{r Libraries, include=FALSE}

library(EDASeq)
library(RUVSeq)
library(RColorBrewer)
library(edgeR)
library(limma)
library(Biobase)
library(SummarizedExperiment)
library(tidyverse) 
library(ggfortify)
library(cluster)
library(edgeR)
library(limma)
library(Homo.sapiens)
library(BiocParallel)
library(qvalue)
library(pheatmap)
library(clusterProfiler)
library(AnnotationDbi)
library(org.Hs.eg.db)
library(RColorBrewer)
library(variancePartition)
library(DOSE)
library(UpSetR)
library(ggvenn)
library(biomaRt)
library(ggridges)
library(reshape2)
library(BioNERO)
library(WGCNA)
library(impute)
library(dynamicTreeCut)
library(enrichplot)
```


# Added funtions 
```{r Added functions}
remove_rows_with_nas <- function(data_frame) {
  data_frame[rowSums(is.na(data_frame)) < 5, ]
}
```


# Steps  
```{r Steps to take}
#* 1. Take Abundance values/counts 
#* 2. Remove NA values from Abundance values 
#* 3. Apply log2 transform to Abundance values 
#* 4. Quantile normalize abundance values 
#* 5. RUVs applied to account for technical variation 
#* 6. Use Limma to model differential protein abundaance 
```


# Read in Data 
```{r Read in Data}

# Load your data
Protein_DF <- read.csv(file = "/Users/omarjohnson/Documents/Projects/Dox_Proteomics/Data/Data_Frames/Abundance.csv", header = TRUE)

# Include metadata about samples 
Meta <- read.csv(file = "/Users/omarjohnson/Documents/Projects/Dox_Proteomics/Data/Data_Frames/Meta.csv", header = TRUE)
```


# Wrangle Data Frame 
```{r Wrangle Data Frame}
# Save the original 
Full_DF <- Protein_DF 


# Subset the columns referring to abundance
Protein_DF_Abundance <- Protein_DF[,c(4, 5:ncol(Protein_DF))] 

# Check for duplicated rows 
# Identify duplicated values
Protein_DF_Abundance$duplicated_name <- duplicated(Protein_DF_Abundance$Accession)

# This will return a logical vector where TRUE indicates the position of duplicates in the column.
# To see only rows with duplicated values, you can subset the dataframe like this:
duplicated_rows <- Protein_DF_Abundance[Protein_DF_Abundance$duplicated_name == TRUE, ]
print(duplicated_rows)

# We have 3 rows with duplicates, two of which have NA values. We will remove them now since we will go ahead 
# and remove the duplicated rows later on anyways. 
Protein_DF_Abundance <- Protein_DF_Abundance[- c(61, 276, 997), ] 

# Make rownames of the data frame accession IDs
rownames(Protein_DF_Abundance) <- Protein_DF_Abundance$Accession

# Change colnames 
colnames(Protein_DF_Abundance)
Protein_DF_Abundance <- Protein_DF_Abundance[, -c(1, 12)]

# Assuming column names of Protein_DF match with the rows in Meta
rownames(Meta) <- Meta$Samples

colnames(Protein_DF_Abundance) <- Meta$Samples
```

# Remove NA values 
```{r Remove NA values }
#1.  Find rows with any NA values
rows_with_na <- apply(Protein_DF_Abundance, 1, function(x) any(is.na(x))) %>% which()
 

rows_with_na <- as.numeric(rows_with_na)
Protein_DF_Abundance %>% dim()

# 2. Remove rows with NA values 
Protein_DF_Abundance <- Protein_DF_Abundance[-rows_with_na, ]

# 3. Sanity check 
Protein_DF_Abundance %>% dim()

```


# Log2 transform
```{r Log2 transform}
log2_norm_counts <- log2(Protein_DF_Abundance)
```

# Quantile Normalization 
```{r Quantile Normalization}
normalizedData <- limma::normalizeBetweenArrays(log2_norm_counts, method = "quantile")
```


# Prepare Data Object for RUVs 
```{r Prepare Data Object for RUVs}
#  counts need to be integer values and in a numeric matrix 
counts <- as.matrix(normalizedData) 

# Create a DataFrame for the phenoData
phenoData <- DataFrame(Meta)

# Now create the RangedSummarizedExperiment necessary for RUVs input 
set <- SummarizedExperiment(assays =  normalizedData, metadata =phenoData)
```


# RUVs Matrix 
```{r RUVs}
# Generate a background matrix where each set of replicates are in a row
# and null spaces where there are replicate mismatches get the value -1. 
# This will be used in the RUVs function, which is the typeII method to
# remove unwanted variation in the RUVs package. This will be used for all 
# RUVs permutations where the number of variation factors will be changed. 
scIdx <- matrix(-1, nrow = 6, ncol = 3)
scIdx[1, 1:3] <- c(which(colnames(counts) %in% c("S6", "S8", "S10"))) # Control group- Technical reps Ind. 48-1
scIdx[2, 1:3] <- c(which(colnames(counts) %in% c("S5", "S7", "S9"))) # Dox group- Technical reps Ind. 48-1
scIdx[3, 1] <- c(which(colnames(counts) %in% c("S2"))) # Control group- Bio reps Ind. 77-1
scIdx[4, 1] <- c(which(colnames(counts) %in% c("S1"))) # Dox group- 77-1
scIdx[5, 1] <- c(which(colnames(counts) %in% c("S4"))) # Control group- Bio reps Ind. 87-1
scIdx[6, 1] <- c(which(colnames(counts) %in% c("S3"))) # Dox group- 87-1
scIdx
```


# Linear Modelling 
```{r Linear Modelling}
# Apply RUVs function from RUVSeq and add to set object
set <- RUVSeq::RUVs(x = normalizedData, k = 1, scIdx = scIdx, isLog = TRUE)
RUV_1 <- set$W[,1]

set$W
phenoData$RUV_1 <- RUV_1


# Create Design Matrix 
# phenoData$Cond <- factor(phenoData$Cond , levels = c("Control", "Dox"))
design <- model.matrix(~0 + Cond + RUV_1, phenoData)
design

# rename columns 
colnames(design) <- c('Control', "Dox", "RUV_1")


# Fit model
fit <- lmFit(set$normalizedCounts, design)
fit2 <- eBayes(fit)


# Make contrasts
cm <- makeContrasts(
  DoxvNorm = Dox - Control,
  levels = design)


# Model with contrasts
fit2 <- contrasts.fit(fit, cm)
fit2 <- eBayes(fit2, robust = TRUE, trend = TRUE)


# Summarize
results_summary <- decideTests(fit2, adjust.method = "none", p.value = 0.05)
summary(results_summary)

# Toptable summary organized to contain results for all tested proteins   
toptable_summary <- topTable(fit2, coef = "DoxvNorm",number = (nrow(set$normalizedCounts )), p.value = 1, adjust.method = "none")
toptable_summary$Protein <- rownames(toptable_summary)
```
# Wrangling for GO
```{r GO wrrangle }
# 1. Read in the comprehensive DF that contains all sample info
Full_DF %>% head()



# 2.
# Get set of DE proteins as per BH adjusted P-value 
DE_proteins_Padj <- toptable_summary %>%
  filter(P.Value < 0.05) %>% rownames()

# Get SYMBOL ID for the proteins in DE_proteins_Padj
# Find the rows where 'var' is in 'values'
rows <- which(Full_DF$Accession %in% DE_proteins_Padj)

# Subset the data frame
subset_Full_data <- Full_DF[rows, ]

# Here are the SYMBOL IDs for the DE proteins as per BH adj P value < 0.05
DE_SYMBOL_Padj <- subset_Full_data$Gene.Symbol %>% unique() %>% na.omit()



# Get background Symbol IDs 
All_proteins_tested <- toptable_summary %>%
  filter(P.Value < 1) %>% rownames()

# Get SYMBOL ID for the proteins in DE_proteins_Padj
# Find the rows where 'var' is in 'values'
rows <- which(Full_DF$Accession %in% All_proteins_tested)

# Subset the data frame
subset_back_data <- Full_DF[rows, ]
Background_SYMBOL <- subset_back_data$Gene.Symbol %>% unique() %>% na.omit() 


```
# GO Enrichment BP
```{r BP}

# 1.
go_enrichment <- enrichGO(gene = DE_SYMBOL_Padj,
                          OrgDb = org.Hs.eg.db,
                          keyType = "SYMBOL",
                          universe = Background_SYMBOL,
                          ont = "BP",
                          pvalueCutoff = 0.05,
                          qvalueCutoff = 0.05)

# Term heirarchy plot 
goplot(go_enrichment, showCategory = 10)


# View the top enriched GO terms as a tibble 
GO_Tibble <- go_enrichment %>% as_tibble()
GO_Tibble




# Arrange by adjusted p value 
GO_Tibble <- GO_Tibble %>%
  arrange(desc(p.adjust))

# Factor by P.adjusted value 
GO_Tibble$Description <- factor(GO_Tibble$Description, levels = GO_Tibble$Description[order(GO_Tibble$p.adjust)])

# Get P value for consistent gradient fill
Gradient_value <- GO_Tibble$qvalue %>% median()

# Visualize the total enriched GO terms using a vertical bar plot 
ggplot(data = GO_Tibble[(nrow(GO_Tibble) - 55):nrow(GO_Tibble) ,], aes(x = -log(p.adjust), y = reorder(Description, -log(p.adjust)))) +
  geom_bar(stat = "identity") + 
  geom_bar(stat = "identity", fill = "#4B9CD3")+
  labs(x = "-log(p-adj)",
       y = "Biologcal Processes",
       fill = "P.adjusted",
       title = "GO enrichment analysis") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))+
  xlim(c(0,100))




edo <- enrichplot::pairwise_termsim(go_enrichment)
emapplot(edo, showCategory = 20, cex_category= 2 )
```


# GO Enrichment MF
```{r MF}
# 1.
go_enrichment <- enrichGO(gene = DE_SYMBOL_Padj,
                          OrgDb = org.Hs.eg.db,
                          keyType = "SYMBOL",
                          universe = Background_SYMBOL,
                          ont = "MF",
                          pvalueCutoff = 0.05,
                          qvalueCutoff = 0.05)

# Go plot 
goplot(go_enrichment, showCategory = 20)


# View the top enriched GO terms as a tibble 
GO_Tibble <- go_enrichment %>% as_tibble()
GO_Tibble



# Arrange by adjusted p value 
GO_Tibble <- GO_Tibble %>%
  arrange(desc(p.adjust))

# Factor by P.adjusted value 
GO_Tibble$Description <- factor(GO_Tibble$Description, levels = GO_Tibble$Description[order(GO_Tibble$p.adjust)])

# Get P value for consistent gradient fill
Gradient_value <- GO_Tibble$qvalue %>% median()

# Visualize the total enriched GO terms using a vertical bar plot 
ggplot(data = GO_Tibble, aes(x = -log(p.adjust), y = reorder(Description, -log(p.adjust)))) +
  geom_bar(stat = "identity") + 
  geom_bar(stat = "identity", fill = "#4B9CD3")+
  labs(x = "-log(p-adj)",
       y = "Biologcal Processes",
       fill = "P.adjusted",
       title = "GO enrichment analysis") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))+
  xlim(c(0,100))



edo <- enrichplot::pairwise_termsim(go_enrichment)
emapplot(edo, showCategory = 15, cex_category=1.5)
```


# GO Enrichment CC  
```{r CC}
# 1.
go_enrichment <- enrichGO(gene = DE_SYMBOL_Padj,
                          OrgDb = org.Hs.eg.db,
                          keyType = "SYMBOL",
                          universe = Background_SYMBOL,
                          ont = "CC",
                          pvalueCutoff = 0.05,
                          qvalueCutoff = 0.05)

goplot(go_enrichment, showCategory = 20)


# View the top enriched GO terms as a tibble 
GO_Tibble <- go_enrichment %>% as_tibble()
GO_Tibble



# Arrange by adjusted p value 
GO_Tibble <- GO_Tibble %>%
  arrange(desc(p.adjust))

# Factor by P.adjusted value 
GO_Tibble$Description <- factor(GO_Tibble$Description, levels = GO_Tibble$Description[order(GO_Tibble$p.adjust)])

# Get P value for consistent gradient fill
Gradient_value <- GO_Tibble$qvalue %>% median()

# Visualize the total enriched GO terms using a vertical bar plot 
ggplot(data = GO_Tibble[(nrow(GO_Tibble) - 20):nrow(GO_Tibble) ,], aes(x = -log(p.adjust), y = reorder(Description, -log(p.adjust)))) +
  geom_bar(stat = "identity") + 
  geom_bar(stat = "identity", fill = "#4B9CD3")+
  labs(x = "-log(p-adj)",
       y = "Biologcal Processes",
       fill = "P.adjusted",
       title = "GO enrichment analysis") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))+
  xlim(c(0,100))


edo <- enrichplot::pairwise_termsim(go_enrichment)
emapplot(edo, showCategory = 15, cex_category=1.5)
```


# Reactome 
```{r Reactome}
# Wrangle ENTREZ IDs for Pval 
# 1. Read in the comprehensive DF that contains all sample info
Full_DF %>% head()


# 2.
# Get set of DE proteins as per BH adjusted P-value 
DE_ENTREZ_Padj <- toptable_summary %>%
  filter(P.Value < 0.05) %>% rownames()

# Get SYMBOL ID for the proteins in DE_proteins_Padj
# Find the rows where 'var' is in 'values'
rows <- which(Full_DF$Accession %in% DE_ENTREZ_Padj)


# Subset the data frame
subset_Full_data <- Full_DF[rows, ]

# Here are the SYMBOL IDs for the DE proteins as per BH adj P value < 0.05
DE_ENTREZ_Padj <- subset_Full_data$Entrez.Gene.ID %>% unique() %>% na.omit()


# Get background Symbol IDs 
All_proteins_tested <- toptable_summary %>%
  filter(P.Value < 1) %>% rownames()

# Get SYMBOL ID for the proteins in DE_proteins_Padj
# Find the rows where 'var' is in 'values'
rows <- which(Full_DF$Accession %in% All_proteins_tested)

# Subset the data frame
subset_back_data <- Full_DF[rows, ]
Background_ENTREZ <- subset_back_data$Entrez.Gene.ID %>% unique() %>% na.omit() 


# Fusion proteins in ENTREZ ids. Therefore, need to split them up 
# vector to split 
my_vector_test <- DE_ENTREZ_Padj


# Split the elements of the vector on semicolons
split_vector <- strsplit(my_vector_test, split = ";")

# Unlist the split vector
new_vector_ENTREZ <- unlist(split_vector)


# Do the same for background 
back_vector_test <- Background_ENTREZ

# Split the elements of the vector on semicolons
split_vector <- strsplit(back_vector_test, split = ";")

# Unlist the split vector
back_new_vector_ENTREZ <- unlist(split_vector)




# Test 
EnrichPathobj <- ReactomePA::enrichPathway(
  new_vector_ENTREZ,
  organism = "human",
  pvalueCutoff = 0.05,
  pAdjustMethod = "BH",
  qvalueCutoff = 0.05,
  universe = back_new_vector_ENTREZ,
  minGSSize = 2,
  maxGSSize = 500,
  readable = FALSE
)



# summary of the result that most people use 
plot(barplot(EnrichPathobj, showCategory = 10 ))

# View the top enriched GO terms as a tibble 
GO_Tibble <- EnrichPathobj %>% as_tibble()


# Arrange by adjusted p value 
GO_Tibble <- GO_Tibble %>%
  arrange(desc(p.adjust))

# Factor by P.adjusted value 
GO_Tibble$Description <- factor(GO_Tibble$Description, levels = GO_Tibble$Description[order(GO_Tibble$p.adjust)])

# Get P value for consistent gradient fill
Gradient_value <- GO_Tibble$qvalue %>% median()

# Visualize the total enriched GO terms using a vertical bar plot 
ggplot(data = GO_Tibble[(nrow(GO_Tibble) - 30):nrow(GO_Tibble) ,], aes(x = -log(p.adjust), y = reorder(Description, -log(p.adjust)))) +
  geom_bar(stat = "identity") + 
  geom_bar(stat = "identity", fill = "#4B9CD3")+
  labs(x = "-log(p-adj)",
       y = "Molecular Functions",
       fill = "P.adjusted",
       title = "GO enrichment analysis") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))+
  xlim(c(0,130))
```